SELECT
	A.ID, A.INPUT_SEQ, A.SKU_CD, A.SKU_NM, A.INPUT_QTY, A.PLAN_QTY, A.RESULT_QTY, CASE WHEN A.PLAN_QTY > A.RESULT_QTY THEN 'R' ELSE 'F' END AS STATUS
FROM (
	SELECT
		I.ID, I.INPUT_SEQ, I.SKU_CD, J.SKU_NM, I.INPUT_QTY, SUM(J.PICK_QTY) AS PLAN_QTY, SUM(J.PICKED_QTY) AS RESULT_QTY
	FROM
		JOB_INPUTS I INNER JOIN JOB_INSTANCES J ON I.DOMAIN_ID = J.DOMAIN_ID AND I.BATCH_ID = J.BATCH_ID AND I.INPUT_SEQ = J.INPUT_SEQ
	WHERE
		I.DOMAIN_ID = :domainId
		AND I.BATCH_ID = :batchId
		#if($equipCd)
		AND J.EQUIP_CD = :equipCd
		#end
		#if($stationCd)
		AND J.SUB_EQUIP_CD IN (SELECT CELL_CD FROM CELLS WHERE DOMAIN_ID = :domainId AND STATION_CD = :stationCd)
		#end
	GROUP BY
		I.ID, I.INPUT_SEQ, I.SKU_CD, J.SKU_NM, I.INPUT_QTY
) A
WHERE
	A.INPUT_SEQ > 0
	#if($status)
	AND A.PLAN_QTY > A.RESULT_QTY
	#end
ORDER BY
	A.INPUT_SEQ DESC