-- TOTAL_ORDER_CNT : 총 주문 수 (출고 : 매장 수, 반품 : 상품 수), ASSIGNED_ORDER_CNT : 할당된 주문 수, REMAIN_ORDER_CNT : 남은 주문 수
-- TOTAL_ORDER_PCS : 총 주문 PCS, ASSIGNED_ORDER_PCS : 할당된 주문 PCS, REMAIN_ORDER_PCS : 남은 주문 PCS

SELECT 
	TOTAL_ORDER_CNT,
	ASSIGNED_ORDER_CNT,
	(TOTAL_ORDER_CNT - ASSIGNED_ORDER_CNT) AS REMAIN_ORDER_CNT,
	TOTAL_ORDER_PCS,
	ASSIGNED_ORDER_PCS,
	(TOTAL_ORDER_PCS - ASSIGNED_ORDER_PCS) AS REMAIN_ORDER_PCS
FROM ( 
	SELECT 
		A.TOTAL_ORDER_CNT,
		NVL(B.ASSIGNED_ORDER_CNT, 0) AS ASSIGNED_ORDER_CNT,
		A.TOTAL_ORDER_PCS,
		NVL(B.ASSIGNED_ORDER_PCS, 0) AS ASSIGNED_ORDER_PCS
	FROM (SELECT
   			BATCH_ID,
			COUNT(DISTINCT(SKU_CD)) AS TOTAL_ORDER_CNT,
			SUM(ORDER_QTY)          AS TOTAL_ORDER_PCS
		FROM
			ORDERS
		WHERE
			DOMAIN_ID = :domainId AND BATCH_ID = :batchId
		GROUP BY 
			BATCH_ID
		) A
           
		LEFT OUTER JOIN
                   
		(SELECT
			BATCH_ID,
			SUM(ASSIGNED_ORDER_CNT) AS ASSIGNED_ORDER_CNT,
			SUM(ASSIGNED_ORDER_PCS / ORDER_CNT) AS ASSIGNED_ORDER_PCS
		FROM (SELECT
				BATCH_ID,
				COUNT(1)       AS ORDER_CNT ,
                1              AS ASSIGNED_ORDER_CNT,
                SUM(TOTAL_PCS) AS ASSIGNED_ORDER_PCS
			FROM
				ORDER_PREPROCESSES
			WHERE
				DOMAIN_ID = :domainId
				AND BATCH_ID = :batchId
				AND EQUIP_CD IS NOT NULL
			GROUP BY 
				BATCH_ID, CELL_ASSGN_CD
			) 
		GROUP BY BATCH_ID) B
	
	ON A.BATCH_ID = B.BATCH_ID
)