INSERT INTO   JOB_INSTANCES
(
       ID,
       BATCH_ID,
       JOB_DATE,
       JOB_SEQ,
       JOB_TYPE,
       COM_CD,
       EQUIP_TYPE,
       EQUIP_CD,
       EQUIP_NM,
       SUB_EQUIP_CD,
       SHOP_CD,
       SHOP_NM,
       ORDER_NO,
       SKU_CD,
       SKU_NM,
       BOX_TYPE_CD,
       INVOICE_ID,
       BOX_IN_QTY,
       ORDER_TYPE,
       DOMAIN_ID,
       STATUS,
       CREATOR_ID,
       UPDATER_ID,
       CREATED_AT,
       UPDATED_AT
)
SELECT   F_GET_GENERATE_UUID() ID,
         BATCH_ID,
         JOB_DATE,
         JOB_SEQ,
         JOB_TYPE,
         COM_CD,
         EQUIP_TYPE,
         NVL(EQUIP_CD,'1') EQUIP_CD,
         EQUIP_NM,
         SUB_EQUIP_CD,
         MAX(SHOP_CD) AS SHOP_CD,
         MAX(SHOP_NM) AS SHOP_NM,
         ORDER_NO,
         SKU_CD,
         SKU_NM,
         BOX_TYPE_CD,
         INVOICE_ID,
         BOX_IN_QTY,
         ORDER_TYPE,
         DOMAIN_ID,
         'RUN',
         'system',
         'system',
         SYSDATE,
         SYSDATE
FROM     ORDERS
WHERE    DOMAIN_ID = :domainId
AND      BATCH_ID  = :batchId
GROUP BY BATCH_ID,
         JOB_DATE,
         JOB_SEQ,
         JOB_TYPE,
         COM_CD,
         EQUIP_TYPE,
         EQUIP_CD,
         EQUIP_NM,
         SUB_EQUIP_CD,
         SHOP_CD,
         SHOP_NM,
         ORDER_NO,
         SKU_CD,
         SKU_NM,
         BOX_TYPE_CD,
         INVOICE_ID,
         BOX_IN_QTY,
         ORDER_TYPE,
         DOMAIN_ID  