WITH TEMP_RACK_ASSIGN AS
( SELECT 
		 BATCH_ID,
		 EQUIP_CD,
         EQUIP_NM
FROM     ORDER_PREPROCESSES
WHERE    DOMAIN_ID = :domainId
AND      BATCH_ID  = :batchId
GROUP BY BATCH_ID,
         EQUIP_CD,
         EQUIP_NM
) 
, TEMP_RACK_SORT AS
( SELECT  
		 BATCH_ID, 
		 EQUIP_CD,
         EQUIP_NM ,
         CASE
                  WHEN EQUIP_CD IS NULL OR EQUIP_CD = ''
                  THEN 100000
                  ELSE RANK() OVER ( ORDER BY EQUIP_CD )
         END AS SORT_COL
FROM     TEMP_RACK_ASSIGN
)
SELECT   
         BATCH_ID,
         EQUIP_CD,
         EQUIP_NM
FROM     TEMP_RACK_SORT
ORDER BY SORT_COL ASC 